import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Memories(),
        ]),
      ),
    );
  }
}

class Memories extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 1008,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFF1B0729)),
          child: Stack(
            children: [
              Positioned(
                left: 146,
                top: 84,
                child: Text(
                  'Memories',
                  style: TextStyle(
                    color: const Color(0xFFFEFEFE),
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 184,
                child: Container(
                  width: 353,
                  height: 464,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 702,
                        top: 0,
                        child: Container(
                          width: 343,
                          height: 464,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 1974,
                                  height: 2961,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://placehold.co/1974x2961"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 200,
                                top: -30,
                                child: Container(
                                  width: 101,
                                  height: 101,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 418,
                                child: Container(
                                  width: 28,
                                  height: 28,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                ),
                              ),
                              Positioned(
                                left: 100,
                                top: 20,
                                child: Text(
                                  'Our First Walk',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF360C51),
                                    fontSize: 35,
                                    fontFamily: 'Amatic SC',
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 144,
                                top: 64,
                                child: Text(
                                  '12/07/2023',
                                  style: TextStyle(
                                    color: const Color(0xFF360C51),
                                    fontSize: 15,
                                    fontFamily: 'Amatica SC',
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 236,
                                child: Container(
                                  width: 343,
                                  height: 228.32,
                                  decoration: BoxDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.50, 0.00),
                                      end: Alignment(0.50, 1.00),
                                      colors: [Colors.black.withValues(alpha: 0), Colors.black, Colors.black],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: -10.75,
                                child: Container(
                                  width: 343,
                                  height: 475.07,
                                  decoration: BoxDecoration(
                                    color: Colors.black.withValues(alpha: 0.10),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 287,
                                child: SizedBox(
                                  width: 305,
                                  child: Text(
                                    '“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse \nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse “',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w300,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 351,
                        top: 0,
                        child: Container(
                          width: 343,
                          height: 464,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 2070,
                                  height: 1380,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://placehold.co/2070x1380"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 106,
                                top: 20,
                                child: Text(
                                  'Our First Trip',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 35,
                                    fontFamily: 'Amatic SC',
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 144,
                                top: 64,
                                child: Text(
                                  '12/09/2023',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 15,
                                    fontFamily: 'Amatica SC',
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 261,
                                child: Container(
                                  width: 343,
                                  height: 203.32,
                                  decoration: BoxDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.50, 0.00),
                                      end: Alignment(0.50, 1.00),
                                      colors: [Colors.black.withValues(alpha: 0), Colors.black, Colors.black],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 41.27,
                                child: Container(
                                  width: 343,
                                  height: 423.05,
                                  decoration: BoxDecoration(
                                    color: Colors.black.withValues(alpha: 0.10),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 23,
                                top: 330,
                                child: SizedBox(
                                  width: 305,
                                  child: Text(
                                    '“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse \nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore “',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w300,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 343,
                          height: 464,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 2070,
                                  height: 1380,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://placehold.co/2070x1380"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 100,
                                top: 38,
                                child: Text(
                                  'Together',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF1B0729),
                                    fontSize: 50,
                                    fontFamily: 'Alex Brush',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 105,
                                top: 92,
                                child: Text(
                                  '- Since 2016 -',
                                  style: TextStyle(
                                    color: const Color(0xFF1B0729),
                                    fontSize: 25,
                                    fontFamily: 'Alex Brush',
                                    fontWeight: FontWeight.w400,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 282,
                                child: Container(
                                  width: 343,
                                  height: 182.32,
                                  decoration: BoxDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.50, 0.00),
                                      end: Alignment(0.50, 1.00),
                                      colors: [Colors.black.withValues(alpha: 0), Colors.black, Colors.black],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 84.97,
                                child: Container(
                                  width: 343,
                                  height: 379.35,
                                  decoration: ShapeDecoration(
                                    color: Colors.black.withValues(alpha: 0.10),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.only(
                                        bottomLeft: Radius.circular(15),
                                        bottomRight: Radius.circular(15),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 357,
                                child: SizedBox(
                                  width: 305,
                                  child: Text(
                                    '“Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse “',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 10,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w400,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 124,
                child: Container(
                  width: 141,
                  height: 30,
                  decoration: ShapeDecoration(
                    gradient: RadialGradient(
                      center: Alignment(0.50, 0.00),
                      radius: 1.00,
                      colors: [const Color(0x26FF9934), const Color(0x0CFF9A34)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: const Color(0xFFFFC300),
                      ),
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 170,
                top: 127,
                child: Text(
                  '19/06/2016',
                  style: TextStyle(
                    color: const Color(0xFFFF9934),
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                    textDecoration: TextDecoration.underline,
                  ),
                ),
              ),
              Positioned(
                left: 140,
                top: 129,
                child: Container(width: 20, height: 20, child: Stack()),
              ),
              Positioned(
                left: 25,
                top: 678,
                child: Text(
                  'Events & Todos',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 718,
                child: Container(
                  width: 343,
                  height: 40,
                  decoration: ShapeDecoration(
                    gradient: RadialGradient(
                      center: Alignment(0.50, -0.00),
                      radius: 1.00,
                      colors: [Colors.white.withValues(alpha: 0.15), Colors.white.withValues(alpha: 0.05)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: Colors.white.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 731,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 33,
                top: 726,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F512700),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 731,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 68,
                top: 727,
                child: Text(
                  'Give Flowers to GF!',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 244,
                top: 731,
                child: Text(
                  '10:00AM • 12/12/25',
                  style: TextStyle(
                    color: const Color(0xFFAEAEAE),
                    fontSize: 10,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 340,
                top: 731,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 0.50, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 768,
                child: Container(
                  width: 343,
                  height: 40,
                  decoration: ShapeDecoration(
                    gradient: RadialGradient(
                      center: Alignment(0.50, -0.00),
                      radius: 1.00,
                      colors: [Colors.white.withValues(alpha: 0.15), Colors.white.withValues(alpha: 0.05)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: Colors.white.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 244,
                top: 781,
                child: Text(
                  '10:00AM • 12/12/25',
                  style: TextStyle(
                    color: const Color(0xFFAEAEAE),
                    fontSize: 10,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 777,
                child: Text(
                  'Moon Gazing',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 781,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 33,
                top: 776,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F512700),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 781,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 340,
                top: 781,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 0.50, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 818,
                child: Container(
                  width: 343,
                  height: 40,
                  decoration: ShapeDecoration(
                    gradient: RadialGradient(
                      center: Alignment(0.50, -0.00),
                      radius: 1.00,
                      colors: [Colors.white.withValues(alpha: 0.15), Colors.white.withValues(alpha: 0.05)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: Colors.white.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 831,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 33,
                top: 826,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F512700),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 831,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 68,
                top: 827,
                child: Text(
                  'Give Flowers to GF!',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 244,
                top: 831,
                child: Text(
                  '10:00AM • 12/12/25',
                  style: TextStyle(
                    color: const Color(0xFFAEAEAE),
                    fontSize: 10,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 340,
                top: 831,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 0.50, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 868,
                child: Container(
                  width: 343,
                  height: 40,
                  decoration: ShapeDecoration(
                    gradient: RadialGradient(
                      center: Alignment(0.50, -0.00),
                      radius: 1.00,
                      colors: [Colors.white.withValues(alpha: 0.15), Colors.white.withValues(alpha: 0.05)],
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: Colors.white.withValues(alpha: 0.50),
                      ),
                      borderRadius: BorderRadius.circular(50),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 244,
                top: 881,
                child: Text(
                  '10:00AM • 12/12/25',
                  style: TextStyle(
                    color: const Color(0xFFAEAEAE),
                    fontSize: 10,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 877,
                child: Text(
                  'Moon Gazing',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 881,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 33,
                top: 876,
                child: Container(
                  width: 25,
                  height: 25,
                  decoration: ShapeDecoration(
                    color: const Color(0x7F512700),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 881,
                child: Container(width: 15, height: 15, child: Stack()),
              ),
              Positioned(
                left: 340,
                top: 881,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(width: 0.50, color: Colors.white),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 338,
                top: 124,
                child: Container(
                  width: 30,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 8,
                        top: 8,
                        child: Container(width: 15, height: 15, child: Stack()),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: ShapeDecoration(
                            color: const Color(0x7F512700),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 0.50,
                                color: const Color(0xFFFFC300),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 8,
                        child: Container(width: 15, height: 15, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 338,
                top: 678,
                child: Container(
                  width: 30,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 8,
                        top: 8,
                        child: Container(width: 15, height: 15, child: Stack()),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: ShapeDecoration(
                            color: const Color(0x7F512700),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 0.50,
                                color: const Color(0xFFFFC300),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 8,
                        top: 8,
                        child: Container(width: 15, height: 15, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 773,
                child: Container(
                  width: 268,
                  height: 52,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 49,
                        top: 12,
                        child: Container(width: 20, height: 20, child: Stack()),
                      ),
                      Positioned(
                        left: 44,
                        top: 32,
                        child: Text(
                          'Home',
                          style: TextStyle(
                            color: const Color(0xFFAEAEAE),
                            fontSize: 10,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 185,
                        top: 0,
                        child: Container(
                          width: 30,
                          height: 30,
                          decoration: ShapeDecoration(
                            color: const Color(0x7F512700),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 0.50,
                                color: const Color(0xFFFFC300),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 175,
                        top: 32,
                        child: Text(
                          'Memories',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 10,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 190,
                        top: 5,
                        child: Container(width: 20, height: 20, child: Stack()),
                      ),
                      Positioned(
                        left: 118,
                        top: 32,
                        child: Text(
                          'Chats',
                          style: TextStyle(
                            color: const Color(0xFFAEAEAE),
                            fontSize: 10,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 116,
                        top: -3,
                        child: Container(width: 35, height: 35, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}